trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'EC2Connection'  # Подключение к EC2
    sourceFolder: '$(System.DefaultWorkingDirectory)'  # Путь к файлам
    contents: '**/*'  # Все файлы проекта
    targetFolder: '/home/ubuntu/WebAppTest/'  # Папка на сервере
    cleanTargetFolder: true  # Очистить перед копированием